version: "3.3"

services:
  app:
    container_name: scammerbots
    build: .
    command: bash bash.sh
    environment:
      API_ID: 21179966
      API_HASH: d97919fb0a3c725e8bb2a25bbb37d57c
      BOT_TOKEN: 7341089553:AAEaPugvHtTNnVSwGwSSlKQhGcb4kQ5-GZY 
      
